# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesArrendatarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientesPropietarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tipo_inmueble', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('numero_habitaciones', models.IntegerField()),
                ('numero_banos', models.IntegerField()),
                ('numero_parqueaderos', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
