# Generated by Django 2.2.1 on 2019-05-16 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ADMIN.Personas'),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='cliente_propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ClientePropietario', to='ADMIN.Personas'),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Representante', to='ADMIN.Personas'),
        ),
    ]
