# Generated by Django 2.2.1 on 2019-05-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0002_auto_20190516_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='cliente_propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ClientePropietarioContrato', to='ADMIN.Personas'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RepresentanteContrato', to='ADMIN.Personas'),
        ),
    ]
