# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ADMIN', '0002_ciudades'),
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_identificacion', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono_movil', models.CharField(max_length=255)),
                ('telefono_fijo', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('valoracion', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='CP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_identificacion', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono_movil', models.CharField(max_length=255)),
                ('telefono_fijo', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('valoracion', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='I',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_propietario', models.IntegerField()),
                ('tipo_inmueble', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('numero_habitaciones', models.IntegerField()),
                ('numero_banos', models.IntegerField()),
                ('numero_parqueaderos', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('latitud', models.CharField(max_length=255)),
                ('longitud', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Ciudades',
        ),
        migrations.DeleteModel(
            name='ClientesArrendatarios',
        ),
        migrations.DeleteModel(
            name='ClientesPropietarios',
        ),
        migrations.DeleteModel(
            name='Inmuebles',
        ),
    ]
