# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ADMIN', '0003_auto_20180725_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i',
            name='cliente_propietario',
            field=models.CharField(max_length=255),
        ),
    ]
