# Generated by Django 2.2.1 on 2019-05-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0003_auto_20190516_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='cliente_arrendatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ClienteArrendatarioContrato', to='ADMIN.Personas'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='InmuebleContrato', to='ADMIN.Inmuebles'),
        ),
    ]
