# Generated by Django 2.2.1 on 2019-05-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0004_auto_20190516_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='codeudor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Codeudor1Contrato', to='ADMIN.Personas'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='codeudor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Codeudor2Contrato', to='ADMIN.Personas'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='codeudor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Codeudor3Contrato', to='ADMIN.Personas'),
        ),
    ]
