# Generated by Django 2.0.7 on 2018-07-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0004_auto_20180727_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='i',
            name='ciudad',
            field=models.CharField(default='CALI', max_length=255),
        ),
        migrations.AddField(
            model_name='i',
            name='pais',
            field=models.CharField(default='COLOMBIA', max_length=255),
        ),
    ]
