# Generated by Django 2.0.7 on 2018-07-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0005_auto_20180727_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='i',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
