# Generated by Django 2.2.1 on 2019-05-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0005_auto_20190516_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AsesorPersona', to='ADMIN.Personas'),
        ),
    ]
