# Generated by Django 2.0.7 on 2018-07-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0006_auto_20180729_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='i',
            name='barrio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='i',
            name='departamento',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='i',
            name='zona',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
