# Generated by Django 2.0.7 on 2018-07-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0007_auto_20180730_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente_propietario', models.IntegerField()),
                ('id_inmueble', models.IntegerField()),
                ('fecha_contrato', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_vigencia', models.DateField()),
                ('precio_canon', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='i',
            name='costo_canon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='i',
            name='precio_canon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
