# Generated by Django 2.0.7 on 2018-08-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0008_auto_20180731_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='c',
            name='id_cliente_arrendatario',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
