# Generated by Django 2.2.1 on 2019-05-18 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ADMIN', '0009_auto_20190517_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='ADMIN.Paises'),
        ),
    ]
