# Generated by Django 2.0.7 on 2018-08-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0009_c_id_cliente_arrendatario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c',
            old_name='id_cliente_arrendatario',
            new_name='cliente_arrendatario',
        ),
        migrations.RenameField(
            model_name='c',
            old_name='id_cliente_propietario',
            new_name='cliente_propietario',
        ),
        migrations.RenameField(
            model_name='c',
            old_name='id_inmueble',
            new_name='inmueble',
        ),
    ]
