# Generated by Django 2.0.7 on 2018-08-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0010_auto_20180801_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c',
            name='cliente_arrendatario',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='c',
            name='cliente_propietario',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='c',
            name='fecha_contrato',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='c',
            name='fecha_inicio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='c',
            name='fecha_vigencia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='c',
            name='inmueble',
            field=models.CharField(max_length=255),
        ),
    ]
