# Generated by Django 2.2.1 on 2019-05-18 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0010_auto_20190517_2345'),
    ]

    operations = [

    ]
